### ISSUE TITLE
OAuth2Strategy requires a authorizationURL option

### ISSUE THREAD

**Issue by remirobert** [drudge/passport-facebook-token#40] opened 2015-11-28 02:19 UTC
Hello,

I need passport-facebook-token, for a mobile authentification.
I made a very simple code snippet to try it. But i got a error, when I execute it.

```Javascript
var facebookTokenStrategy = require('passport-facebook-token').Strategy;

app.use(passport.initialize());
app.use(passport.session());

passport.use(
    new facebookTokenStrategy(
        {
            clientID: '9008***',
            clientSecret: 'f8979***9',
            profileFields: ['id', 'email', 'displayName', 'photos']

        }, 
        function(accessToken, refreshToken, profile, done) {
            return done(null, {
                provider: 'facebook',
                id:'asdfSADFSDFsdfsdfsdfSDFSDFSDF',
                displayName:profile._json.name,
                name: {},
                emails: [
                    {value:profile._json.email, type:'home'}
                ],
                photos: []
            });
        }
    )
);

app.get('/', passport.authenticate('facebook-token'), function (req, res) {
     res.json({
        'message': 'Hello World'
    });
});
```

When I want la run the server I got this error : 
```
TypeError: OAuth2Strategy requires a authorizationURL option
```

I looked on internet, I need to provide some env variables, so I also changed the to run the server : 
```
BASE_URL="localhost:3000" FACEBOOK_KEY=93200 FACEBOOK_SECRET=f3217949 node app.js
```

Still having the same issue.
Thanks in advance for you helps. :+1: 

ps :  If I can't find any solution with passport-facebook-token, can you give me some tips to accomplish a login/signup Facebook based only with the access token ?

**Comment by ghaiklor** [comment] 2015-11-28 08:38
Guys, really, read the docs before creating an issue.
@remirobert https://github.com/drudge/passport-facebook-token#usage. You are importing the strategy wrong. There is no `Strategy` in package. Package itself is a Strategy.

**Comment by remirobert** [comment] 2015-12-01 07:12
I have tried that before. I got this result : 

```
InternalOAuthError: Failed to fetch user profile
   at /Users/remirobert/Downloads/passport-facebook-mobile-example-develop/node_modules/passport-facebook-token/lib/index.js:147:32
   at ClientRequest.<anonymous> (/Users/remirobert/Downloads/passport-facebook-mobile-example-develop/node_modules/passport-facebook-token/node_modules/passport-oauth/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:148:5)
   at ClientRequest.emit (events.js:107:17)
   at TLSSocket.socketErrorListener (_http_client.js:271:9)
   at TLSSocket.emit (events.js:129:20)
   at net.js:459:14
   at process._tickCallback (node.js:355:11)
```

**Comment by ghaiklor** [comment] 2015-12-01 08:18
@remirobert check your token in [Graph Explorer](https://developers.facebook.com/tools/explorer)

**Comment by remirobert** [comment] 2015-12-01 08:20
It's good, I got a response object : 

```son
{
  "id": "575063",
  "name": "Remi Robert"
}
```

**Comment by ghaiklor** [comment] 2015-12-01 08:28
@remirobert provide your passport configuration and verify function. Also how are you sending token?

**Comment by remirobert** [comment] 2015-12-01 08:31
This is how I configure passport : 

```javascript
var passport = require('passport');
var facebookTokenStrategy = require('passport-facebook-token');
var express = require('express');

var app = express();

console.log(process.env);

app.use(passport.initialize());
app.use(passport.session());

passport.serializeUser(function(user, done) {
  done(null, user);
});

passport.deserializeUser(function(user, done) {
  done(null, user);
});
```

Now, this is the request : 
This is a POST request:
```
http://127.0.0.1:3000/facebook?access_token=CPqrEp8kGHBhAbZBpUVykoSBuacSciPqFYT09Etb0fU0LZCq82XvqhALZCVH93ETfByt3wV1Ljh1w1jGgtvFH1itiazq8b76iBSu7tmendCqK58p2Kd87Egw
```

And the express route : 
```javascript
app.post('/facebook', passport.authenticate('facebook-token'), function (req, res) {
    console.log(req);
     res.json({
        'message': 'Hello World'
    });
});
```

**Comment by ghaiklor** [comment] 2015-12-01 08:39
@remirobert seems you are doing correct on the first look. I'll try to reproduce bug with http request.

**Comment by remirobert** [comment] 2015-12-01 08:48
@ghaiklor Thank you so much for your support. :+1:

**Comment by ghaiklor** [comment] 2015-12-01 11:45
@remirobert I have publish new version with a little fixes. Was trying to reproduce your bug but unsuccessful. With my access token everything is working great.

**Comment by remirobert** [comment] 2015-12-02 02:30
Can please send me the code you used. If you have different initialisation than me ?

**Comment by ghaiklor** [comment] 2015-12-02 13:43
@remirobert usual access token, nothing special.

**Comment by remirobert** [comment] 2015-12-02 14:10
It seems I get some 401 error from my POST request.

**Comment by remirobert** [comment] 2015-12-02 14:12
After 3 full days on it. Impossible to get something. I create severals Facebook apps, checked permissions. Tried with a dozen of different access token. I really don't what's going on. And I didn't see any other implementation with passport.

I am totally lost...

**Comment by duanmua** [comment] 2015-12-03 08:35
@remirobert I ran into a similar issue just now, possibly the same one:

I see you started off testing with a GET at '/' which didn't work for you. This was the case for me as well.

You later switched to adding on `.Strategy` on the package, using POST and using '/facebook' instead of '/'

I would suggest going back to the straight package import, and the very basic example one shown in the README but using the path in that example or another one that isn't '/'

I wonder if the `access_token` url param is not handled correctly when it comes after a slash, as it would be forced to `blah.com/?access_token=` in browers as opposed to `blah.com/facebook?access_token=` for any other request

**Comment by ghaiklor** [comment] 2015-12-03 08:47
@remirobert @duanmua BTW, guys, do you understand that when you send data in URL query you should use GET request but not POST? I'm using this module in all of our projects and works without any issues.

**Comment by duanmua** [comment] 2015-12-03 08:57
@ghaiklor Yup, I've only been using GET in my testing so far. Most frameworks ought to support them in POST too, though certainly it isn't good practice.

I've got no problems now, everything is working fine for me as well

**Comment by ghaiklor** [comment] 2015-12-03 09:05
@duanmua not exactly. When you are making POST with `route?key=value` it doesn't recognize these data, because it's GET data. For instance, Express has 2 different properties for that - `body` and `query`.

**Comment by Zertz** [comment] 2015-12-22 00:53
@ghaiklor I ran into the same issue and didn't notice this change when going through the docs. This is a case where a changelog is useful for existing users :)

If you'd like, I can create a PR to get one up and running. Was it introduced in 2.0 or 3.0?

**Comment by ghaiklor** [comment] 2015-12-22 07:48
@Zertz 3.0 was entirely rewritten, I suppose in 3.0.

**Comment by ghaiklor** [comment] 2016-01-03 19:24
Seems that there is no issues, based on 

> I've got no problems now, everything is working fine for me as well

So I'm closing this issue.

**Closed by ghaiklor** 2016-01-03 19:24 UTC

**Comment by marcorm** [comment] 2016-01-30 16:24
@remirobert Hi guys.. i was facing the same issue.
Simply i was asking the token to facebook with a different APP ID and APP SECRET then the one i use for authenticating. Make sure you use the same APP ID and SECRET when you fetch the token.

Hope this helps

**Comment by aquartier** [comment] 2016-11-28 19:08
const facebookTokenStrategy = require('passport-facebook-token')
without .Strategy after require.

**Comment by chrischen-melb** [comment] 2017-05-10 02:17
I'm the another one here who puts .Strategy at the end 😂
